base: 'https://demo.typo3.org/'
baseVariants:
  -
    base: 'https://demo.typo3.dev/'
    condition: 'applicationContext == "Production/Content"'
  -
    base: 'https://demo.typo3.org.ddev.site/'
    condition: 'applicationContext == "Development/DDEV"'
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=29'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=49'
  -
    errorCode: 500
    errorHandler: Page
    errorContentSource: 't3://page?uid=50'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: EN
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
  -
    title: German
    enabled: true
    languageId: 1
    base: /de/
    typo3Language: de
    locale: de_DE.utf8
    iso-639-1: de
    navigationTitle: DE
    hreflang: de
    direction: ltr
    flag: de
    websiteTitle: ''
    fallbackType: strict
    fallbacks: ''
  -
    title: Hebrew
    enabled: true
    base: /he/
    typo3Language: he
    locale: he_IL.UTF-8
    iso-639-1: he
    websiteTitle: ''
    navigationTitle: HE
    hreflang: he
    direction: rtl
    fallbackType: strict
    fallbacks: ''
    flag: il
    languageId: 2
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      resettimer.html: 1603464133342
      sitemap.xml: 1533906435
routes:
  -
    route: robots.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\n\r\nSitemap: https://demo.typo3.org/sitemap.xml"
  -
    route: google34eb0c66f374609a.html
    type: staticText
    content: 'google-site-verification: google34eb0c66f374609a.html'
sitePackage: site_t3demo
websiteTitle: ''
